import React from "react";

export default function Home() {
  return (
    <>
      <h2>Welcome to ACME Stocks</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id justo in dui consequat molestie. Aliquam pellentesque luctus vehicula. Duis a sagittis est, ac interdum elit. Aenean et dictum purus. Maecenas ultricies nunc vitae laoreet tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam in malesuada ligula, aliquam ullamcorper lorem. Sed eget viverra ante, ac fermentum eros. Quisque vitae diam ut magna egestas rhoncus. Praesent in gravida sapien, ac tristique purus. In dolor quam, dictum vel odio id, dignissim varius lacus. Proin molestie augue sed aliquam maximus. Morbi faucibus, odio in posuere pellentesque, lorem lacus posuere risus, nec tempus metus justo et quam. Quisque blandit facilisis purus, gravida luctus arcu consectetur vitae. Fusce pellentesque pellentesque mi, quis suscipit turpis dictum sed. Proin eu velit tincidunt, ultrices magna vitae, sodales odio.</p>
      <p>Curabitur laoreet bibendum dui et hendrerit. Donec dignissim est eget ligula pharetra, et commodo felis condimentum. Donec bibendum iaculis justo sed vestibulum. Vivamus in ligula sapien. Suspendisse pulvinar mi placerat maximus tempor. Fusce justo ante, sagittis nec mauris sed, malesuada dignissim lorem. Cras mauris nisl, interdum sed tincidunt at, tincidunt ut arcu. Nunc sed imperdiet augue, ac rhoncus lectus.</p>
      <p>Donec porta commodo neque, at semper elit finibus et. Phasellus pellentesque vehicula justo vel lacinia. Etiam condimentum dui est, ut pharetra nisl scelerisque nec. Etiam sagittis, lorem at aliquet bibendum, metus mi porta lorem, et iaculis nisi quam in libero. In vel molestie leo. Mauris lorem justo, placerat sollicitudin risus non, malesuada fringilla risus. Vivamus posuere nisi erat, ut suscipit tortor consectetur sed. Sed blandit orci eu justo fringilla, vel ultrices risus rutrum.</p>
      <p>Fusce vitae lorem quis ipsum sodales rhoncus. Praesent sollicitudin tincidunt fermentum. In in varius magna, at rutrum felis. Nullam convallis dolor in lorem ultrices, eu ullamcorper augue pulvinar. Aliquam urna libero, ullamcorper sed feugiat at, bibendum in eros. Mauris consectetur id risus ut vehicula. Morbi varius nisl mauris, vitae ultricies nunc auctor sit amet. Ut malesuada mauris id dolor interdum ornare. Suspendisse nibh lorem, accumsan eget lorem a, malesuada luctus massa. Sed et aliquam ligula. Aliquam vel velit dignissim, faucibus justo at, venenatis velit. Nunc nibh sem, malesuada consequat laoreet vel, commodo eget quam. Aliquam facilisis est quis commodo lobortis. Donec dapibus, lorem id luctus aliquam, magna felis lobortis magna, ac placerat augue massa et quam. Maecenas aliquam auctor consequat.</p>
      <p>Nulla ornare dolor purus, et euismod neque maximus ut. Sed eu pharetra nisi. Nullam vel iaculis mi. Ut in pellentesque purus. Vestibulum sagittis tincidunt erat, sed gravida urna iaculis a. Morbi molestie ultrices turpis, hendrerit sagittis metus scelerisque ut. Vestibulum turpis erat, ornare eget ipsum nec, maximus maximus purus. Aenean at blandit nulla. Integer eu ligula vel justo fermentum rhoncus nec sit amet ante. Donec dictum nulla tortor, suscipit facilisis mi molestie quis. </p>
      <img src="/finance-chart.jpg" width="100%" alt="finance chart"/>
    </>
  )
}
